name: benchmark

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          check-latest: true
          cache: true
      - name: Benchmark
        run: make bench
