name: cover

on: [push]

permissions:
  contents: read

jobs:
  test:

    name: Upload coverage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: '**/go.sum'

      - name: Download dependencies
        run: go mod download

      - name: Make coverage
        run: make cover

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
